name = "Combina"
uuid = "bb583df9-be0c-4202-8a4a-0c9563e1e548"
authors = ["Alberto De Marchi"]
version = "0.0.1"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
